"""fixed: user table

Revision ID: 1bf9c1de2ac8
Revises: 53ef00802f5d
Create Date: 2022-08-04 07:41:42.236678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf9c1de2ac8'
down_revision = '53ef00802f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approved', sa.Boolean(), nullable=True))
    op.drop_column('user', 'passowrd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passowrd', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'approved')
    # ### end Alembic commands ###
