"""added: password field to user table

Revision ID: 257124a8102a
Revises: 1bf9c1de2ac8
Create Date: 2022-08-04 07:43:06.980700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257124a8102a'
down_revision = '1bf9c1de2ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
